In [25]:
import pandas as pd
import dotenv
import os

In [26]:
dotenv.load_dotenv('../../.env')
SWEEP_EXP_DIR=os.getenv("SWEEP_EXP_DIR")
SWEEP_ANALYSIS_DIR=os.getenv("SWEEP_ANALYSIS_DIR")
DEEPLOC2_OUTPUT_DIR=os.getenv("DEEPLOC2_OUTPUT_DIR")
MULOCDEEP_MODELS_DIR=os.getenv("MULOCDEEP_MODELS_DIR")
LAPROTT5_OUTPUT=os.getenv("LAPROTT5_OUTPUT")
RANDOM_OUTPUT=os.getenv("RANDOM_OUTPUT")

In [27]:
#Choose if you are combining results for single-localizing proteins, multi-localizing proteins or all proteins
SINGLE = False
MULTI = True

In [28]:
test_avgs = []
test_perclass_level1 = []
test_perclass_level2 = []
test_perclass_level3 = []
val_avgs = []
val_perclass_level1 = []
val_perclass_level2 = []
val_perclass_level3 = []

In [29]:
#mulocdeep_path = "/hai/scratch/zwefers/seq2loc/mulocdeep/models/combined_trainset/seq2loc_level1_3/outputs"
mulocdeep_path = f"{MULOCDEEP_MODELS_DIR}/seq2loc_level1_3/outputs"

if SINGLE:
    mulocdeep_path= mulocdeep_path +"/single_label"
elif MULTI:
    mulocdeep_path= mulocdeep_path +"/multi_label"

test_avg_metrics = pd.read_csv(f"{mulocdeep_path}/test_avg_metrics.csv")
test_avg_metrics["model"] = "MULocDeep_13"
test_avgs.append(test_avg_metrics)
test_perclass_metrics_level1 = pd.read_csv(f"{mulocdeep_path}/test_perclass_metrics_level1.csv")
test_perclass_metrics_level1["model"] = "MULocDeep_13"
test_perclass_metrics_level1.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level3 = pd.read_csv(f"{mulocdeep_path}/test_perclass_metrics_level3.csv")
test_perclass_metrics_level3["model"] = "MULocDeep_13"
test_perclass_metrics_level3.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level3.append(test_perclass_metrics_level3)

val_avg_metrics = pd.read_csv(f"{mulocdeep_path}/val_avg_metrics.csv")
val_avg_metrics["model"] = "MULocDeep_13"
val_avgs.append(val_avg_metrics)
val_perclass_metrics_level1 = pd.read_csv(f"{mulocdeep_path}/val_perclass_metrics_level1.csv")
val_perclass_metrics_level1["model"] = "MULocDeep_13"
val_perclass_metrics_level1.rename({"labels": "label"}, axis=1, inplace=True)
val_perclass_level1.append(val_perclass_metrics_level1)
val_perclass_metrics_level3 = pd.read_csv(f"{mulocdeep_path}/val_perclass_metrics_level3.csv")
val_perclass_metrics_level3["model"] = "MULocDeep_13"
val_perclass_metrics_level3.rename({"labels": "label"}, axis=1, inplace=True)
val_perclass_level3.append(val_perclass_metrics_level3)

In [30]:
#mulocdeep_path = "/hai/scratch/zwefers/seq2loc/mulocdeep/models/combined_trainset/seq2loc_level1_2/outputs"
mulocdeep_path = f"{MULOCDEEP_MODELS_DIR}/seq2loc_level1_2/outputs"

if SINGLE:
    mulocdeep_path= mulocdeep_path +"/single_label"
elif MULTI:
    mulocdeep_path= mulocdeep_path +"/multi_label"

test_avg_metrics = pd.read_csv(f"{mulocdeep_path}/test_avg_metrics.csv")
test_avg_metrics["model"] = "MULocDeep_12"
test_avgs.append(test_avg_metrics)

test_perclass_metrics_level1 = pd.read_csv(f"{mulocdeep_path}/test_perclass_metrics_level1.csv")
test_perclass_metrics_level1["model"] = "MULocDeep_12" 
test_perclass_metrics_level1.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level2 = pd.read_csv(f"{mulocdeep_path}/test_perclass_metrics_level2.csv")
test_perclass_metrics_level2["model"] = "MULocDeep_12"
test_perclass_metrics_level2.rename({"labels": "label"}, axis=1, inplace=True)

test_perclass_level2.append(test_perclass_metrics_level2)

val_avg_metrics = pd.read_csv(f"{mulocdeep_path}/val_avg_metrics.csv")
val_avg_metrics["model"] = "MULocDeep_12"
val_avgs.append(val_avg_metrics)
val_perclass_metrics_level1 = pd.read_csv(f"{mulocdeep_path}/val_perclass_metrics_level1.csv")
val_perclass_metrics_level1["model"] = "MULocDeep_12"
val_perclass_metrics_level1.rename({"labels": "label"}, axis=1, inplace=True)
val_perclass_level1.append(val_perclass_metrics_level1)
val_perclass_metrics_level2 = pd.read_csv(f"{mulocdeep_path}/val_perclass_metrics_level2.csv")
val_perclass_metrics_level2["model"] = "MULocDeep_12"
val_perclass_metrics_level2.rename({"labels": "label"}, axis=1, inplace=True)
val_perclass_level2.append(val_perclass_metrics_level2)

In [31]:
if SINGLE:
    tag="_single"
elif MULTI:
    tag="_multi"
else:
    tag = ""

#dl2_path = "/hai/scratch/zwefers/seq2loc/deeploc2/outputs/seq2locbench/esm1"
dl2_path = f"{DEEPLOC2_OUTPUT_DIR}/esm1"

test_avg_metrics = pd.read_csv(f"{dl2_path}/test_metrics_avg{tag}.csv")
test_avg_metrics["model"] = "DeepLoc2-ESM1"
test_avgs.append(test_avg_metrics)
test_perclass_metrics_level1 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level1{tag}.csv")
test_perclass_metrics_level1["model"] = "DeepLoc2-ESM1"
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level2 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level2{tag}.csv")
test_perclass_metrics_level2["model"] = "DeepLoc2-ESM1"
test_perclass_level2.append(test_perclass_metrics_level2)
test_perclass_metrics_level3 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level3{tag}.csv")
test_perclass_metrics_level3["model"] = "DeepLoc2-ESM1"
test_perclass_level3.append(test_perclass_metrics_level3)


val_avg_metrics = pd.read_csv(f"{dl2_path}/val_metrics_avg{tag}.csv")
val_avg_metrics["model"] = "DeepLoc2-ESM1"
val_avgs.append(val_avg_metrics)
val_perclass_metrics_level1 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level1{tag}.csv")
val_perclass_metrics_level1["model"] = "DeepLoc2-ESM1"
val_perclass_level1.append(val_perclass_metrics_level1)
val_perclass_metrics_level2 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level2{tag}.csv")
val_perclass_metrics_level2["model"] = "DeepLoc2-ESM1"
val_perclass_level2.append(val_perclass_metrics_level2)
val_perclass_metrics_level3 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level3{tag}.csv")
val_perclass_metrics_level3["model"] = "DeepLoc2-ESM1"
val_perclass_level3.append(val_perclass_metrics_level3)

In [32]:
#dl2_path = "/hai/scratch/zwefers/seq2loc/deeploc2/outputs/seq2locbench/prott5"
dl2_path = f"{DEEPLOC2_OUTPUT_DIR}/prott5"


if SINGLE:
    tag="_single"
elif MULTI:
    tag="_multi"
else:
    tag = ""

test_avg_metrics = pd.read_csv(f"{dl2_path}/test_metrics_avg{tag}.csv")
test_avg_metrics["model"] = "DeepLoc2-ProtT5"
test_avgs.append(test_avg_metrics)
test_perclass_metrics_level1 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level1{tag}.csv")
test_perclass_metrics_level1["model"] = "DeepLoc2-ProtT5"
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level2 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level2{tag}.csv")
test_perclass_metrics_level2["model"] = "DeepLoc2-ProtT5"
test_perclass_level2.append(test_perclass_metrics_level2)
test_perclass_metrics_level3 = pd.read_csv(f"{dl2_path}/test_metrics_perclass_level3{tag}.csv")
test_perclass_metrics_level3["model"] = "DeepLoc2-ProtT5"
test_perclass_level3.append(test_perclass_metrics_level3)

val_avg_metrics = pd.read_csv(f"{dl2_path}/val_metrics_avg{tag}.csv")
val_avg_metrics["model"] = "DeepLoc2-ProtT5"
val_avgs.append(val_avg_metrics)
val_perclass_metrics_level1 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level1{tag}.csv")
val_perclass_metrics_level1["model"] = "DeepLoc2-ProtT5"
val_perclass_level1.append(val_perclass_metrics_level1)
val_perclass_metrics_level2 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level2{tag}.csv")
val_perclass_metrics_level2["model"] = "DeepLoc2-ProtT5"
val_perclass_level2.append(val_perclass_metrics_level2)
val_perclass_metrics_level3 = pd.read_csv(f"{dl2_path}/val_metrics_perclass_level3{tag}.csv")
val_perclass_metrics_level3["model"] = "DeepLoc2-ProtT5"
val_perclass_level3.append(val_perclass_metrics_level3)

In [33]:
#Reconfigure LAProtT5 results
cols = ["acc", "macro_ap", "micro_ap", "f1_macro", "f1_micro", "jaccard_macro", "jaccard_micro", "rocauc_macro", "rocauc_micro", "mlrap", "cov_error", "num_labels", "level", "model"]

if SINGLE:
    tag="_single"
elif MULTI:
    tag="_multi"
else:
    tag = ""

test_avg_metrics = pd.read_csv(f"{LAPROTT5_OUTPUT}/LAProtT5_avg_metrics{tag}.csv")
test_avg_metrics.rename({"coverage_error": "cov_error"}, axis=1, inplace=True)
test_avg_metrics.loc[:, "level"] = test_avg_metrics.category_level.apply(lambda x: str(x[-1]))
test_avg_metrics["model"] = "LAProtT5"
test_avg_metrics = test_avg_metrics[cols]
test_avgs.append(test_avg_metrics)
cols = ["mcc_perclass", "acc_perclass", "recall_perclass", "precision_perclass", "f1_perclass", "jaccard_perclass", "rocauc_perclass", "label", "model"]
test_perclass_metrics_level1 = pd.read_csv(f"{LAPROTT5_OUTPUT}/LAProtT5_perclass_metrics_level1{tag}.csv")
test_perclass_metrics_level1.rename(
    {"category": "label",
    "location": "label",
    "mcc": "mcc_perclass",
    "acc": "acc_perclass",
    "recall": "recall_perclass",
    "precision": "precision_perclass",
    "f1": "f1_perclass",
    "jaccard": "jaccard_perclass",
    "rocauc": "rocauc_perclass"}, axis=1, inplace=True)
test_perclass_metrics_level1["model"] = "LAProtT5"
test_perclass_metrics_level1 = test_perclass_metrics_level1[cols]
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level2 = pd.read_csv(f"{LAPROTT5_OUTPUT}/LAProtT5_perclass_metrics_level2{tag}.csv")
test_perclass_metrics_level2.rename(
    {"category": "label",
    "location": "label",
    "mcc": "mcc_perclass",
    "acc": "acc_perclass",
    "recall": "recall_perclass",
    "precision": "precision_perclass",
    "f1": "f1_perclass",
    "jaccard": "jaccard_perclass",
    "rocauc": "rocauc_perclass"}, axis=1, inplace=True)
test_perclass_metrics_level2["model"] = "LAProtT5"
test_perclass_metrics_level2 = test_perclass_metrics_level2[cols]
test_perclass_level2.append(test_perclass_metrics_level2)
test_perclass_metrics_level3 = pd.read_csv(f"{LAPROTT5_OUTPUT}/LAProtT5_perclass_metrics_level3{tag}.csv")
test_perclass_metrics_level3.rename(
    {"category": "label",
    "location": "label",
    "mcc": "mcc_perclass",
    "acc": "acc_perclass",
    "recall": "recall_perclass",
    "precision": "precision_perclass",
    "f1": "f1_perclass",
    "jaccard": "jaccard_perclass",
    "rocauc": "rocauc_perclass"}, axis=1, inplace=True)
test_perclass_metrics_level3["model"] = "LAProtT5"
test_perclass_metrics_level3 = test_perclass_metrics_level3[cols]
test_perclass_level3.append(test_perclass_metrics_level3)

In [34]:
#Collect results for random baseline
if SINGLE:
    tag="_single"
elif MULTI:
    tag="_multi"
else:
    tag = ""

test_avg_metrics = pd.read_csv(f"{RANDOM_OUTPUT}/random_avg_metrics{tag}.csv")
test_avg_metrics["model"] = "Random"
test_avgs.append(test_avg_metrics)
test_perclass_metrics_level1 = pd.read_csv(f"{RANDOM_OUTPUT}/random_perclass_metrics_level1{tag}.csv")
test_perclass_metrics_level1["model"] = "Random"
test_perclass_metrics_level1.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level1.append(test_perclass_metrics_level1)
test_perclass_metrics_level2 = pd.read_csv(f"{RANDOM_OUTPUT}/random_perclass_metrics_level2{tag}.csv")
test_perclass_metrics_level2["model"] = "Random"
test_perclass_metrics_level2.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level2.append(test_perclass_metrics_level2)
test_perclass_metrics_level3 = pd.read_csv(f"{RANDOM_OUTPUT}/random_perclass_metrics_level3{tag}.csv")
test_perclass_metrics_level3["model"] = "Random"
test_perclass_metrics_level3.rename({"labels": "label"}, axis=1, inplace=True)
test_perclass_level3.append(test_perclass_metrics_level3)

In [35]:
test_avgs = pd.concat(test_avgs)
test_perclass_level1 = pd.concat(test_perclass_level1)
test_perclass_level2 = pd.concat(test_perclass_level2)
test_perclass_level3 = pd.concat(test_perclass_level3)

val_avgs = pd.concat(val_avgs)
val_perclass_level1 = pd.concat(val_perclass_level1)
val_perclass_level2 = pd.concat(val_perclass_level2)
val_perclass_level3 = pd.concat(val_perclass_level3)

In [36]:
test_avgs

,macro_ap,micro_ap,acc,f1_macro,f1_micro,jaccard_macro,jaccard_micro,rocauc_macro,rocauc_micro,mlrap,cov_error,num_labels,level,model,Unnamed: 0
0,0.289561,0.674062,0.055164,0.275170,0.483941,0.186378,0.319210,0.802750,0.879647,0.774047,6.253521,3.636150,1,MULocDeep_13,NaN
1,0.650802,0.794295,0.301643,0.577027,0.694505,0.421071,0.531987,0.822654,0.892643,0.859219,3.052817,1.645540,3,MULocDeep_13,NaN
0,0.299596,0.694576,0.075117,0.268826,0.514685,0.182491,0.346516,0.790535,0.892520,0.788148,5.884977,2.714789,1,MULocDeep_12,NaN
1,0.537430,0.786757,0.271127,0.480673,0.679055,0.344178,0.514068,0.801963,0.909159,0.847943,3.264085,1.631455,2,MULocDeep_12,NaN
0,0.348922,0.428155,0.053991,0.317361,0.494776,0.218953,0.494776,0.807486,0.837617,0.614147,6.907277,3.633803,1,DeepLoc2-ESM1,NaN
1,0.563096,0.730610,0.224236,0.511566,0.666078,0.369714,0.666078,0.838575,0.887105,0.812551,3.402039,1.754247,2,DeepLoc2-ESM1,NaN
2,0.689773,0.754404,0.265127,0.604645,0.700331,0.446022,0.700331,0.836423,0.869922,0.832448,3.116612,1.573157,3,DeepLoc2-ESM1,NaN
0,0.345871,0.388622,0.039906,0.316213,0.485741,0.218874,0.485741,0.801675,0.825381,0.588278,7.125587,3.894366,1,DeepLoc2-ProtT5,NaN
1,0.568375,0.725725,0.233296,0.522583,0.684746,0.383030,0.684746,0.840576,0.888462,0.814744,3.364666,1.917327,2,DeepLoc2-ProtT5,NaN
2,0.693360,0.757822,0.240924,0.612835,0.695441,0.451944,0.695441,0.846167,0.875748,0.838109,3.080308,1.532453,3,DeepLoc2-ProtT5,NaN
0,0.310361,0.717488,0.122112,0.271224,0.540499,0.184136,0.540499,0.813509,0.919583,0.816209,4.491749,2.081408,1,LAProtT5,NaN
1,0.514044,0.838449,0.196920,0.446989,0.663566,0.320222,0.663566,0.839081,0.935736,0.874656,2.930693,1.487349,2,LAProtT5,NaN
2,0.617079,0.839733,0.247525,0.499255,0.692602,0.366591,0.692602,0.844580,0.921181,0.889533,2.818482,1.363036,3,LAProtT5,NaN
0,NaN,NaN,0.027655,0.085287,0.307709,0.051492,0.181870,NaN,NaN,NaN,NaN,1.557228,1,Random,0.0
1,NaN,NaN,0.037586,0.173586,0.351233,0.107085,0.213076,NaN,NaN,NaN,NaN,1.424523,2,Random,0.0
2,NaN,NaN,0.039719,0.226342,0.364412,0.140015,0.222851,NaN,NaN,NaN,NaN,1.398986,3,Random,0.0

In [37]:
display(test_avgs[
    (test_avgs.model.isin(["MULocDeep_13", "MULocDeep_12"])) &
    (test_avgs.level==1)
    ])
# MULocDeep_12 is better on level 1 for all metrics --> drop MULocDeep_12 for level1

test_avgs = test_avgs[~((test_avgs.model == "MULocDeep_13") & (test_avgs.level==1))]
val_avgs = val_avgs[~((val_avgs.model == "MULocDeep_13") & (val_avgs.level==1))]

test_perclass_level1 = test_perclass_level1[test_perclass_level1.model != "MULocDeep_13"]
val_perclass_level1 = val_perclass_level1[val_perclass_level1.model != "MULocDeep_13"]

#Rename MULocDeep models
test_avgs.loc[test_avgs.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
test_perclass_level1.loc[test_perclass_level1.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
test_perclass_level2.loc[test_perclass_level2.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
test_perclass_level3.loc[test_perclass_level3.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
val_avgs.loc[val_avgs.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
val_perclass_level1.loc[val_perclass_level1.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
val_perclass_level2.loc[val_perclass_level2.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"
val_perclass_level3.loc[val_perclass_level3.model.isin(["MULocDeep_13", "MULocDeep_12"]), "model"] = "MULocDeep"

,macro_ap,micro_ap,acc,f1_macro,f1_micro,jaccard_macro,jaccard_micro,rocauc_macro,rocauc_micro,mlrap,cov_error,num_labels,level,model,Unnamed: 0
0,0.289561,0.674062,0.055164,0.275170,0.483941,0.186378,0.319210,0.802750,0.879647,0.774047,6.253521,3.636150,1,MULocDeep_13,NaN
0,0.299596,0.694576,0.075117,0.268826,0.514685,0.182491,0.346516,0.790535,0.892520,0.788148,5.884977,2.714789,1,MULocDeep_12,NaN

In [38]:
save_dir = f"../../Benchmark-Models/results/"
if not os.path.exists(f"{save_dir}/test_avgs{tag}.csv"):
    test_avgs.to_csv(f"{save_dir}/test_avgs{tag}.csv", index=False)
    test_perclass_level1.to_csv(f"{save_dir}/test_perclass_level1{tag}.csv", index=False)
    test_perclass_level2.to_csv(f"{save_dir}/test_perclass_level2{tag}.csv", index=False)
    test_perclass_level3.to_csv(f"{save_dir}/test_perclass_level3{tag}.csv", index=False)

if not os.path.exists(f"{save_dir}/val_avgs{tag}.csv"):
    val_avgs.to_csv(f"{save_dir}/val_avgs{tag}.csv", index=False)
    val_perclass_level1.to_csv(f"{save_dir}/val_perclass_level1{tag}.csv", index=False)
    val_perclass_level2.to_csv(f"{save_dir}/val_perclass_level2{tag}.csv", index=False)
    val_perclass_level3.to_csv(f"{save_dir}/val_perclass_level3{tag}.csv", index=False)